# NOTE: for Rishi, basically we want to enter a link, have a "loading animation", and then 
# generate a nicely formatted PDF report, with mapped coordinates, confidence values for each, and then 
# the general report generated by Gemini/Chat which hoepfully includes people, places, things, etc.
# If it does then maybe also add a table or smth to the pdf with "key information"
# which lists best geo-guess, key people

import streamlit as st
from urllib.parse import urlparse
import time
from AggregrationLayer import AggregationLayer
from ExtractionLayer import ExtractionLayer
from ConclusionLayer import ConclusionLayer
from dotenv import load_dotenv


# --------------- Initialization ----------------
load_dotenv()

# Keep these visible as pipeline scaffolding for each layer owner.
extraction_layer = None
aggregation_layer = None
conclusion_layer = None
# ===============================================

def is_valid_url(url: str) -> bool:
    """
    Basic URL validation for frontend input.
    """
    try:
        parsed = urlparse(url.strip())
        return parsed.scheme in {"http", "https"} and bool(parsed.netloc)
    except ValueError:
        return False


st.set_page_config(page_title="GeoInference Enhancement Pipeline", layout="wide")
st.title("GeoInference Enhancement Pipeline")
st.write("Enter a webpage URL to begin geolocation analysis.")

default_url = st.session_state.get("input_url", "")
input_url = st.text_input("Website URL", value=default_url, placeholder="https://example.com/article")
analyze_clicked = st.button("Analyze", type="primary")

if analyze_clicked:
    if not input_url.strip():
        st.error("Please enter a URL before running analysis.")
    elif not is_valid_url(input_url):
        st.error("Please enter a valid URL that starts with http:// or https://.")
    else:
        st.session_state["input_url"] = input_url.strip()

        with st.spinner("Analyzing input..."):
            time.sleep(1.2)

        # -------------- Extraction Logic ---------------
        # For now, only pass URL into ExtractionLayer.
        extraction_layer = ExtractionLayer(url=input_url.strip())
        # TODO: extraction_results = extraction_layer.run()
        # ===============================================


        # -------------- Aggregation Logic ---------------
        # TODO: aggregation_layer = AggregationLayer()
        # TODO: relevant_content = aggregation_layer.extract_relevant_page_content(page_content=...)
        # TODO: gps_coordinate_guesses = aggregation_layer.infer_geolocation(image_path=...) # for single image, will need to loop if multiple images exist
        # ===============================================


        # -------------- Conclusion Logic ---------------
        # TODO: conclusion_layer = ConclusionLayer()
        # TODO: final_report = conclusion_layer.generate_report(...)
        conclusion_layer = ConclusionLayer()
 
        final_report = conclusion_layer.generate_report(
        relevant_content=relevant_content,       # str  — from aggregation_layer.extract_relevant_page_content()
        gps_guesses=gps_coordinate_guesses,      # dict — from aggregation_layer.infer_geolocation()
        metadata=extraction_results["metadata"], # dict — from extraction_layer.run(), may be {}
        image_path=extraction_results["image_path"],  # str — saved image path
        )
        
        # What final_report looks like (pass these pieces to Rishi for the PDF/UI)
        # -----------------------------------------------------------------------
        #
        # final_report = {
        #
        #   "location_guesses": [
        #       {
        #           "rank": 1,
        #           "location_name": "Rome, Lazio, Italy",
        #           "coordinates": [41.9028, 12.4964],
        #           "confidence": 0.87,
        #           "reasoning": "Colosseum visible in background; Italian text in site content; ..."
        #       },
        #       { "rank": 2, ... },
        #       ...
        #   ],
        #
        #   "conflict_analysis": "EXIF GPS points to Vatican City (41.9022, 12.4539), 
        #                          which is ~4 km from GeoClip's top guess of central Rome. 
        #                          This is a minor conflict — both suggest the same metro area.",
        #
        #   "key_information": {
        #       "best_guess": "Rome, Italy",
        #       "key_people":  ["Pope Francis"],
        #       "key_places":  ["Colosseum", "Vatican City", "Piazza Venezia"],
        #       "key_events":  ["Easter Mass 2024"],
        #       "confidence_summary": "High confidence (~87%) — image content, metadata, 
        #                              and GeoClip all converge on central Rome."
        #   },
        #
        #   "full_report": "The image depicts ... [2-4 paragraph prose for the PDF]"
        # }
        
        # ===============================================

        st.success("Input captured and passed to ExtractionLayer.")
        st.caption(f"ExtractionLayer initialized with URL: {extraction_layer.url}")
        st.info(
            "Pipeline execution is scaffolded only. Extraction/Aggregation/Conclusion methods are pending wiring."
        )
