# NOTE: for Rishi, basically we want to enter a link, have a "loading animation", and then 
# generate a nicely formatted PDF report, with mapped coordinates, confidence values for each, and then 
# the general report generated by Gemini/Chat which hoepfully includes people, places, things, etc.
# If it does then maybe also add a table or smth to the pdf with "key information"
# which lists best geo-guess, key people

import streamlit as st
from AggregrationLayer import AggregationLayer
from ExtractionLayer import ExtractionLayer
from ConclusionLayer import ConclusionLayer
from dotenv import load_dotenv

# --------------- Initialization ----------------
load_dotenv()

extraction_layer = ExtractionLayer(url="")
aggregation_layer = AggregationLayer()
conclusion_layer = ConclusionLayer()

# ===============================================


# -------------- Extraction Logic ---------------
# TODO: Put whatever the execution logic is for this here
# ===============================================


# -------------- Aggregation Logic ---------------
relevant_content = aggregation_layer.extract_relevant_page_content(page_content="")
gps_coordinate_guesses = aggregation_layer.infer_geolocation(image_path="")

print(gps_coordinate_guesses)
# ===============================================


# -------------- Conclusion Logic ---------------
# TODO: Put whatever the conclusion logic is for this here
# ===============================================


# run with steamlit run main.py

# st.set_page_config(layout="wide")

# st.title("GeoInference Enhancement Pipeline")